title: Aesthetic, earthy perspective of the world around
description: Hey! Welcome. Myname is Aravind Krishnan and this is my personal website. I want to share my perspectives about the world around me.
show_downloads: true
google_analytics:
theme: 
