title: Aesthetic, earthy perspective of the world
description: My name is Aravind Krishnan and this is my personal website. I want to share my perspectives on things that intrigue me.
theme: jekyll-theme-midnight
